### ISSUE TITLE
Add support for Roles

### ISSUE THREAD

**Issue by ryanlangton** [darrencauthon/MvcTurbine.MembershipProvider#3]
Needs support for Roles added.

**Comment by darrencauthon** [comment]
What is a Role?

**Comment by darrencauthon** [comment]
Oh, if you're talking about the "IsInRole" method (or whatever it was called), it already supports it.

You just have to create your own IPrincipalProvider, instead of inheriting from the regular PrincipalProvider (ugh, I hate writing that sentence).  And then in your own IPrincipalProvider, you can construct the principal however you want -- including setting roles or making it inherit from five levels of GenericPrincipal or whatever. :)

**Comment by ryanlangton** [comment]
Ok I thought something might need added to TicketData since I didn't see a way to reconstruct the IPrincipal with Roles currently with just the stored Username.  I'm adding the roles to UserData however, that should suffice.

**Comment by darrencauthon** [comment]
Yeah, that's how I've used it in the past.  UserData is just one big string, so you can put whatever you want.  For my own use, I'd put in a comma-separated list of data that I'd need to use when creating the instance of the IPrincipal.
